# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14ca03f9330b5c15f434fa225aa1893732ef2844e0b3b6b68951053276332bb625603cc9d62c6c42d02151c660db6e0ee78ca0303a62a83007f7a77bd618d755

test:
  secret_key_base: 72f2b3aa43a2e691a68fe75ebde8c3760c37a810c16a9b1d3dec74a1c2e3e886dac84fff2d76082c223df9340c7d415bb6271b2b1b42899ad5451c031055ca5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
